import type { NextPage } from "next";
import Head from "next/head";
import { Home as HomeContainer } from "@enlear/bit-landing-page-template.pages.home";
import dynamic from "next/dynamic";

const HeroContent = dynamic(() => import("../src/home/hero-content"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer
        heroContent={<HeroContent />}
        statistics={[
          {
            label: "Components",
            value: 1000,
            suffix: "+",
          },
          {
            label: "Contributors",
            value: 1000,
            suffix: "+",
          },
          {
            label: "Teams",
            value: 1000,
            suffix: "+",
          },
          {
            label: "Companies",
            value: 1000,
            suffix: "+",
          },
        ]}
      />
    </>
  );
};

export default Home;
